export const PROFILE_TEXT = {
  ro: {
    page_title: "MathHard — Profil",

    logo_slogan: "Profil",
    back_home: "Înapoi",

    account_kicker: "Profil MathHard",
    visitor: "Vizitator",
    not_logged_yet: "Nu ești logat.",

    badge_lessons: "Lecții",
    badge_problems: "Probleme",
    badge_xp: "XP",
    badge_exams: "Examene",

    auth_title: "Cont",
    auth_text_guest: "Autentifică-te pentru a-ți păstra progresul.",
    auth_text_connected: "Cont conectat.",

    email_label: "Email",
    password_label: "Parolă",
    display_name_signup_label: "Nume afișat",

    password_placeholder: "Parola ta",
    display_name_signup_placeholder: "ex: Cristi",

    login_btn: "Autentificare",
    signup_btn: "Creează cont",
    logout_btn: "Deconectare",

    status_label: "Status:",
    status_guest: "Guest",
    status_logged_in: "Logat",

    solved_label: "Probleme rezolvate",
    read_label: "Lecții citite",
    learned_label: "Lecții învățate",
    passed_label: "Examene promovate",
    xp_total_label: "XP total",

    account_data_title: "Date cont",
    info_display_name: "Nume afișat",
    info_email: "Email",
    info_confirmed: "Email confirmat",

    progress_title: "Rezumat progres",
    progress_lessons_read: "Lecții citite",
    progress_lessons: "Lecții învățate",
    progress_problems: "Probleme rezolvate",
    progress_exams: "Examene promovate",
    avg_xp: "XP mediu / problemă rezolvată",

    detailed_title: "Statistici detaliate",
    detail_solved: "Probleme rezolvate",
    detail_attempted: "Probleme încercate",
    detail_opened: "Probleme deschise",
    detail_unopened: "Probleme nedeschise",
    detail_lessons_learned: "Lecții învățate",
    detail_lessons_read_only: "Citite, de verificat",
    detail_lessons_unread: "Lecții necitite",
    detail_exams_passed: "Examene promovate",
    detail_exams_unpassed: "Examene încercate, dar nepromovate",
    detail_exams_unattempted: "Examene neîncercate",

    next_title: "Ce urmează",
    next_lesson: "Următoarea lecție",
    next_chapter: "Următorul capitol",
    next_exam: "Următorul examen recomandat",

    recent_title: "Activitate recentă",
    recent_lesson: "Ultima lecție",
    recent_problem: "Ultima problemă rezolvată",
    recent_exam: "Ultimul examen",

    extra_exam_title: "Performanță examene",
    best_exam: "Cel mai bun examen",
    exam_attempts: "Încercări totale la examene",
    last_exam_score: "Ultimul scor de examen",

    settings_title: "Cont și profil",
    settings_text: "Actualizează datele publice și securitatea contului.",

    community_kicker: "Comunitate",
    community_title: "Profil public",
    community_intro: "Construiește profilul care va apărea în comunitate și în clasamente.",
    community_open: "Deschide profilul",
    community_save: "Salvează",
    community_identity_title: "Identitate",
    community_identity_help: "Câmpurile principale ale profilului.",
    community_username_label: "Username",
    community_username_hint: "3–24 caractere: litere mici, cifre, punct, minus sau underscore.",
    community_display_name: "Nume afișat",
    community_avatar: "Avatar URL",
    community_banner: "Banner URL",
    community_bio: "Bio",
    community_location_title: "Locație și educație",
    community_location_help: "Locația exactă și școala nu sunt solicitate.",
    community_country: "Țară",
    community_region: "Județ / regiune",
    community_education_level: "Nivel educațional",
    community_grade: "Clasă / an",
    community_study_track: "Profil / specializare",
    community_goal: "Obiectiv academic",
    community_unspecified_f: "Nespecificată",
    community_unspecified_m: "Nespecificat",
    community_middle_school: "Gimnaziu",
    community_high_school: "Liceu",
    community_university: "Facultate",
    community_graduate: "Master / Doctorat",
    community_teacher: "Profesor",
    community_other: "Altul",
    community_personality_title: "Matematică și personalitate",
    community_personality_help: "Câmpuri opționale pentru un profil mai personal.",
    community_current_focus: "Învăț acum",
    community_favorite_topics: "Capitole favorite",
    community_favorite_mathematician: "Matematician favorit",
    community_favorite_theorem: "Teoremă favorită",
    community_languages: "Limbi",
    community_quote: "Citat",
    community_links_title: "Linkuri și stil",
    community_links_help: "Linkurile apar numai dacă activezi vizibilitatea lor.",
    community_website: "Website",
    community_github: "GitHub",
    community_portfolio: "Portofoliu",
    community_accent: "Culoare profil",
    community_theme: "Stil profil",
    community_featured_badge: "Badge principal",
    community_auto: "Automat",
    community_privacy_title: "Confidențialitate",
    community_privacy_help: "Profilul și clasamentele sunt opt-in.",
    community_public: "Profil public",
    community_public_help: "Permite afișarea paginii tale publice.",
    community_leaderboard: "Participă în clasamente",
    community_leaderboard_help: "Necesită un profil public.",
    community_privacy_location: "Locație",
    community_privacy_location_help: "Țară și regiune.",
    community_privacy_education: "Educație",
    community_privacy_education_help: "Nivel, clasă și obiectiv.",
    community_privacy_personality: "Matematică și personalitate",
    community_privacy_personality_help: "Preferințe, focus, limbi și citat.",
    community_privacy_progress: "Progres",
    community_privacy_progress_help: "Lecții, probleme și examene.",
    community_privacy_badges: "Badge-uri",
    community_privacy_badges_help: "Roluri și contribuții.",
    community_privacy_achievements: "Realizări",
    community_privacy_achievements_help: "Realizări de progres.",
    community_privacy_streak: "Streak",
    community_privacy_streak_help: "Activitatea consecutivă.",
    community_privacy_links: "Linkuri",
    community_privacy_links_help: "Website, GitHub și portofoliu.",
    community_privacy_activity: "Activitate",
    community_privacy_activity_help: "Data înscrierii și ultima activitate.",
    edit_display_name: "Nume afișat",
    edit_avatar_url: "Avatar URL (opțional)",
    edit_new_password: "Parolă nouă",

    edit_display_name_placeholder: "ex: Cristi",
    edit_avatar_url_placeholder: "https://...",
    edit_new_password_placeholder: "Noua parolă",

    save_profile_btn: "Salvează profilul",
    reset_profile_btn: "Resetează profilul",
    change_password_btn: "Schimbă parola",
    delete_account_btn: "Șterge contul",

    yes: "Da",
    no: "Nu",
    fallback_user: "User",

    processing: "Se procesează...",
    must_login: "Trebuie să fii logat.",
    display_name_empty: "Numele afișat nu poate fi gol.",
    avatar_url_invalid: "URL-ul avatarului trebuie să înceapă cu http:// sau https://.",
    saving_profile: "Se salvează profilul...",
    profile_updated: "Profil actualizat.",
    save_profile_error: "Nu am putut salva profilul: {error}",

    new_password_short: "Parola nouă trebuie să aibă minim 6 caractere.",
    changing_password: "Se schimbă parola...",
    password_changed: "Parola a fost schimbată.",
    password_change_error: "Eroare la schimbarea parolei: {error}",

    reset_confirm: "Sigur vrei să resetezi datele profilului? Numele afișat va reveni la fallback-ul din email și avatarul va fi golit.",
    resetting_profile: "Se resetează profilul...",
    profile_reset: "Profil resetat.",
    profile_reset_error: "Nu am putut reseta profilul: {error}",

    delete_confirm: "Sigur vrei să ștergi contul complet? Această acțiune este ireversibilă.",
    deleting_account: "Se șterge contul...",
    delete_unconfirmed: "Funcția nu a confirmat ștergerea contului.",
    account_deleted: "Cont șters complet.",
    delete_error: "Eroare delete account: {error}",

    fill_email_password: "Completează emailul și parola.",
    signing_up: "Se creează contul...",
    already_same_email: "Ești deja logat cu acest email. Pentru cont nou, folosește alt email.",
    signup_error: "Eroare signup: {error}",
    signup_check_email: "Cont creat. Verifică emailul pentru confirmare, apoi fă login.",

    logging_in: "Se face login...",
    already_logged_this_account: "Ești deja logat cu acest cont.",
    login_error: "Eroare login: {error}",

    logging_out: "Se face logout...",
    logged_out: "Te-ai delogat.",
    logout_error: "Eroare logout: {error}",

    auth_success: "Autentificat cu succes.",
    progress_load_error: "Progresul nu a putut fi încărcat momentan.",
    auth_refresh_error: "Sesiunea nu a putut fi actualizată.",
    initial_load_error: "Profilul nu a putut fi încărcat momentan.",

    all_lessons_done: "Ai terminat toate lecțiile 🎉",
    nothing_left: "Nimic restant",
    retry_exam: "Reîncearcă: {exam}",
    all_exams_done: "Ai terminat toate examenele 🎉",

    best_word: "scor maxim",
    last_word: "ultimul scor"
  },

  en: {
    page_title: "MathHard — Profile",

    logo_slogan: "Profile",
    back_home: "Back",

    account_kicker: "MathHard Profile",
    visitor: "Visitor",
    not_logged_yet: "You are not logged in.",

    badge_lessons: "Lessons",
    badge_problems: "Problems",
    badge_xp: "XP",
    badge_exams: "Exams",

    auth_title: "Account",
    auth_text_guest: "Sign in to keep your progress.",
    auth_text_connected: "Account connected.",

    email_label: "Email",
    password_label: "Password",
    display_name_signup_label: "Display name",

    password_placeholder: "Your password",
    display_name_signup_placeholder: "e.g. Cristi",

    login_btn: "Sign in",
    signup_btn: "Create account",
    logout_btn: "Sign out",

    status_label: "Status:",
    status_guest: "Guest",
    status_logged_in: "Logged in",

    solved_label: "Problems solved",
    read_label: "Lessons read",
    learned_label: "Lessons learned",
    passed_label: "Exams passed",
    xp_total_label: "Total XP",

    account_data_title: "Account details",
    info_display_name: "Display name",
    info_email: "Email",
    info_confirmed: "Email confirmed",

    progress_title: "Progress summary",
    progress_lessons_read: "Lessons read",
    progress_lessons: "Lessons learned",
    progress_problems: "Problems solved",
    progress_exams: "Exams passed",
    avg_xp: "Average XP / solved problem",

    detailed_title: "Detailed stats",
    detail_solved: "Problems solved",
    detail_attempted: "Problems attempted",
    detail_opened: "Problems opened",
    detail_unopened: "Problems not opened",
    detail_lessons_learned: "Lessons learned",
    detail_lessons_read_only: "Read, check pending",
    detail_lessons_unread: "Unread lessons",
    detail_exams_passed: "Exams passed",
    detail_exams_unpassed: "Exams attempted but not passed",
    detail_exams_unattempted: "Exams not attempted",

    next_title: "What's next",
    next_lesson: "Next lesson",
    next_chapter: "Next chapter",
    next_exam: "Next recommended exam",

    recent_title: "Recent activity",
    recent_lesson: "Latest lesson",
    recent_problem: "Latest solved problem",
    recent_exam: "Latest exam",

    extra_exam_title: "Exam performance",
    best_exam: "Best exam",
    exam_attempts: "Total exam attempts",
    last_exam_score: "Last exam score",

    settings_title: "Account and profile",
    settings_text: "Update your public details and account security.",

    community_kicker: "Community",
    community_title: "Public profile",
    community_intro: "Build the profile shown in the community and leaderboards.",
    community_open: "Open profile",
    community_save: "Save",
    community_identity_title: "Identity",
    community_identity_help: "The main fields of your profile.",
    community_username_label: "Username",
    community_username_hint: "3–24 characters: lowercase letters, numbers, dot, hyphen or underscore.",
    community_display_name: "Display name",
    community_avatar: "Avatar URL",
    community_banner: "Banner URL",
    community_bio: "Bio",
    community_location_title: "Location and education",
    community_location_help: "Your exact location and school are not requested.",
    community_country: "Country",
    community_region: "State / province / region",
    community_education_level: "Education level",
    community_grade: "Grade / year",
    community_study_track: "Study track",
    community_goal: "Academic goal",
    community_unspecified_f: "Not specified",
    community_unspecified_m: "Not specified",
    community_middle_school: "Middle school",
    community_high_school: "High school",
    community_university: "University",
    community_graduate: "Master's / PhD",
    community_teacher: "Teacher",
    community_other: "Other",
    community_personality_title: "Mathematics and personality",
    community_personality_help: "Optional fields that make your profile more personal.",
    community_current_focus: "Currently learning",
    community_favorite_topics: "Favorite topics",
    community_favorite_mathematician: "Favorite mathematician",
    community_favorite_theorem: "Favorite theorem",
    community_languages: "Languages",
    community_quote: "Quote",
    community_links_title: "Links and style",
    community_links_help: "Links appear only when you enable their visibility.",
    community_website: "Website",
    community_github: "GitHub",
    community_portfolio: "Portfolio",
    community_accent: "Profile color",
    community_theme: "Profile style",
    community_featured_badge: "Featured badge",
    community_auto: "Automatic",
    community_privacy_title: "Privacy",
    community_privacy_help: "Public profiles and leaderboards are opt-in.",
    community_public: "Public profile",
    community_public_help: "Allows your public profile page to be displayed.",
    community_leaderboard: "Join leaderboards",
    community_leaderboard_help: "Requires a public profile.",
    community_privacy_location: "Location",
    community_privacy_location_help: "Country and region.",
    community_privacy_education: "Education",
    community_privacy_education_help: "Level, grade and goal.",
    community_privacy_personality: "Mathematics and personality",
    community_privacy_personality_help: "Preferences, current focus, languages and quote.",
    community_privacy_progress: "Progress",
    community_privacy_progress_help: "Lessons, problems and exams.",
    community_privacy_badges: "Badges",
    community_privacy_badges_help: "Roles and contributions.",
    community_privacy_achievements: "Achievements",
    community_privacy_achievements_help: "Learning achievements.",
    community_privacy_streak: "Streak",
    community_privacy_streak_help: "Consecutive activity.",
    community_privacy_links: "Links",
    community_privacy_links_help: "Website, GitHub and portfolio.",
    community_privacy_activity: "Activity",
    community_privacy_activity_help: "Join date and last activity.",
    edit_display_name: "Display name",
    edit_avatar_url: "Avatar URL (optional)",
    edit_new_password: "New password",

    edit_display_name_placeholder: "e.g. Cristi",
    edit_avatar_url_placeholder: "https://...",
    edit_new_password_placeholder: "New password",

    save_profile_btn: "Save profile",
    reset_profile_btn: "Reset profile",
    change_password_btn: "Change password",
    delete_account_btn: "Delete account",

    yes: "Yes",
    no: "No",
    fallback_user: "User",

    processing: "Processing...",
    must_login: "You must be logged in.",
    display_name_empty: "Display name cannot be empty.",
    avatar_url_invalid: "The avatar URL must start with http:// or https://.",
    saving_profile: "Saving profile...",
    profile_updated: "Profile updated.",
    save_profile_error: "Could not save profile: {error}",

    new_password_short: "The new password must be at least 6 characters long.",
    changing_password: "Changing password...",
    password_changed: "Password changed.",
    password_change_error: "Password change error: {error}",

    reset_confirm: "Are you sure you want to reset your profile data? Your display name will fall back to the email and the avatar will be cleared.",
    resetting_profile: "Resetting profile...",
    profile_reset: "Profile reset.",
    profile_reset_error: "Could not reset profile: {error}",

    delete_confirm: "Are you sure you want to delete the entire account? This action is irreversible.",
    deleting_account: "Deleting account...",
    delete_unconfirmed: "The function did not confirm account deletion.",
    account_deleted: "Account deleted completely.",
    delete_error: "Delete account error: {error}",

    fill_email_password: "Fill in email and password.",
    signing_up: "Creating account...",
    already_same_email: "You are already logged in with this email. Use another email for a new account.",
    signup_error: "Signup error: {error}",
    signup_check_email: "Account created. Check your email for confirmation, then log in.",

    logging_in: "Logging in...",
    already_logged_this_account: "You are already logged into this account.",
    login_error: "Login error: {error}",

    logging_out: "Logging out...",
    logged_out: "You have logged out.",
    logout_error: "Logout error: {error}",

    auth_success: "Authenticated successfully.",
    progress_load_error: "Progress could not be loaded right now.",
    auth_refresh_error: "The session could not be refreshed.",
    initial_load_error: "The profile could not be loaded right now.",

    all_lessons_done: "You finished all lessons 🎉",
    nothing_left: "Nothing left",
    retry_exam: "Retry: {exam}",
    all_exams_done: "You finished all exams 🎉",

    best_word: "best",
    last_word: "last"
  }
};
